### PR TITLE
fix: Use `posthog.api` to fetch and create annotations

### LINKED ISSUE #14: Error when using in Posthog cloud
## Context
We got the error below after enabling this plugin in Posthog
```plain
TypeError: Cannot read properties of undefined (reading 'map')
    at runEveryMinute (vm.js:73:53)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I found something that may be related in the source code:
https://github.com/PostHog/github-release-tracking-plugin/blob/main/index.js#L69

Does there have an endpoint ended with `/git/refs/tags`? I can't find it in GitHub Doc. [This](https://docs.github.com/en/rest/git/refs#update-a-reference) is the closest one I found

### PR DESCRIPTION
**Pull request by pjhul**
This app has been broken for quite some time by the changes to our API, which a number of users noted in #14. To fix this, I've gone through and used the `posthog.api` util to fetch and create annotations, along with a number of other changes. 

### Changes
- Swap `fetch` calls for `posthog.api` util when fetching/creating annotations
- Removes the config checks in `setupPlugin` - Feel free to let me know if you think this should still be here, but I feel I remember Karl noting that we should try and avoid network requests in `setupPlugin`. May be totally misinterpreting this though!
- Changes to use Typescript

Closes #14

### CODE REVIEW

**Comment by mariusandra** [comment]
The reason this used `runEveryMinute` in the first place is to avoid this effect:

1. Enable plugin
2. Wait for stuff to happen
3. ...
4. ???
5. Profit!?

Unless there's a job to manually trigger with instructions on how to do so, you will have really slow feedback when enabling this plugin.

**Comment by pjhul** [comment]
Ahhh that makes sense, totally agree now that you mention it. I'll go back and re-enable this 👍

**Comment by joepavitt** [comment]
Is there any update on this please? Just enabled the plugin and hitting the issue detailed in #14

**Comment by pjhul** [comment]
I've gone through and tested this myself and given that the app is completely broken right now I'm going to merge this 👍

**Comment by joepavitt** [comment]
what is the process for this becoming available in Posthog Cloud instance? Does a build/release get automatically kicked off, it take from `main` by default, or anything more manual I need to do?

**Comment by pjhul** [comment]
Nope, the newest version should be available on Cloud now and you shouldn't need to do anything else other than updating the configuration. 

(Note that you'll need to put in both a Personal API key and a Project API key into the config, but I'll be removing this requirement in the future once some other issues get resolved)

**Pull request merged**
